### ISSUE TITLE
按文档启动ca服务报错

### ISSUE THREAD

**Issue by ChinaArJun** [sxguan/fabric-network#2]
2021/08/06 16:23:00 [DEBUG] Closing server DBs
Error: Failed to find private key for certificate in '/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem': Could not find matching private key for SKI: Failed getting key for SKI [[139 72 245 38 116 37 37 241 105 29 217 186 186 99 43 184 244 183 173 46 210 135 27 158 103 32 211 187 55 55 171 87]]: Key with SKI 8b48f526742525f1691dd9baba632bb8f4b7ad2ed2871b9e6720d3bb3737ab57 not found in /etc/hyperledger/fabric-ca-server/msp/keystore

**Comment by ChinaArJun** [comment]
解决了，需要手动修改/fabric-network/crypto-config/peerOrganizations/org1.example.com/tlsca和ca下面的*_sk文件为priv_sk

**Comment by Merlin0126** [comment]
nice... Thanks
